name: CYTNoteblockRegion
version: '${version}'
main: com.lukemango.cytnoteblockregion.CYTNoteblockRegion
api-version: 1.19
depend: [ NoteBlockAPI, WorldGuard ]
authors: [ lukemango ]
description: Play noteblock songs to players in worldguard regions
website: craftyourtown.com
